### ISSUE TITLE
UniverseToObject does not return Universe as an Object

### ISSUE THREAD

**Issue by mtraeger** [wiedi/node-dmx#23]
UniverseToObject (https://github.com/wiedi/node-dmx/blob/master/dmx.js#L43) does only send an empty object in my setup. I only evaluated it via calling https://github.com/wiedi/node-dmx/blob/master/dmx-web.js#L116 where the initial sending of values does not work. 

The cause might be in Line 46 (https://github.com/wiedi/node-dmx/blob/master/dmx.js#L46) where universe.length is used. In my setup it does not return the length of the universe but an object. I fixed it by using 512 instead of universe.length. 

On Blank-Project with artnet-driver:
```
console.log(universe.length) //<Buffer 02 00>
console.dir(universe.length) //Buffer { '0': 2, '1': 0 }
```

**Comment by wiedi** [comment]
thank you for your analysis, should be fixed now.
