### ISSUE TITLE
How does this connect to visualization software?

### ISSUE THREAD

**Issue by AdamMikacich** [wiedi/node-dmx#27]
Hello,
    Does node-dmx have any support for connecting to visualization software? If so, what softwares are supported and how do I send the output to both the visualization and usb to dmx adapter? Thanks in advance.

**Comment by wiedi** [comment]
I'm not sure in which way you want to connect to node-dmx.
For input node-dmx provides the javascript API and a web API. As an output you can use artnet for example.

A Light Controlling Software making use of node-dmx would be EasyCue: http://davidhoare.net/easycue/index.html

I hope this helps.
