### ISSUE TITLE
Can this library be used as a Server?

### ISSUE THREAD

**Issue by haysclark** [wiedi/node-dmx#28]
I was hoping to intercept DMX messages from a piece of software, and then translate the message to a LIFX bulb. It looks like this library is intended to be a 'client', which controls DMX units? Is this correct?

**Comment by wiedi** [comment]
It can be used as a library (`dmx.js`) in other software or you can use the included webserver (`dmx-web.js`). It implements the dmx controller part, so devices on the DMX bus react to messages generated by it.

I hope this answers your question, if not please clarify what you mean by "client". :)
