### ISSUE TITLE
Where can I find the dmx-web.json ?

### ISSUE THREAD

**Issue by MarvinLa** [wiedi/node-dmx#29]
I always get the error: Cannot find the module '/etc/dmx-web.json'.
What is the dmx-web.json and where can I find it?

**Comment by drscream** [comment]
Hello @MarvinLa,

based on the documentation (README.md) it should be:

> A example configuration is in the repository by the name dmx-web-example.conf

This file could be copied to `/etc/dmx-web.json` but maybe a modification is required.

Best regards!
