### ISSUE TITLE
Broadcast on artnet

### ISSUE THREAD

**Issue by Joebayld** [wiedi/node-dmx#40]
I need to enable broadcast on the artnet driver. I added this code to make it work. 

```
self.dev.on('listening', function(){
    self.dev.setBroadcast(true);
});
```

Should we add it to the master? Or maybe have an option to enable broadcast?

**Comment by wiedi** [comment]
The setBroadcast() call seems reasonable.
Is the event handler for 'listening' actually required or could we just do setBroadcast directly below the `self.dev = dgram.createSocket('udp4')` line?

**Comment by Joebayld** [comment]
I tried adding it below and it didn’t work. Upon research, I found this solution and it works. 

Joe

**Comment by wiedi** [comment]
ok great, thanks for confirming that. Do you want to create a pull request?

**Comment by wiedi** [comment]
merged, thanks!
