### ISSUE TITLE
Problem running dmx-web.js 

### ISSUE THREAD

**Issue by pavan4** [wiedi/node-dmx#5]
Hi all, 

I tried to install the library and run the sample. I have a problem here : 

    app.configure(function() {
              app.use(connect.json());
    })

I read that configure method has been removed from express. So I removed the configure to just use 

    app.use(connect.json());

I couldn't run the app So I commented this part as well and the app runs now. But I am not sure what this connect.json() does. Can this be omitted?

**Comment by wiedi** [comment]
node-dmx still uses the express 3 api.
If used with the versions from package.json everything should work.

If this doesn't fix your problem feel free to reopen this issue.
