### ISSUE TITLE
updateAll for enttec-usb-dmx-pro driver

### ISSUE THREAD

**Issue by pavan4** [wiedi/node-dmx#6]
Hi 

I have an ENTTEC DMXUSB PRO and would like to use this to drive some dmx lights. I installed all the packages correctly and I am able to run the demo and light up some dmx lights.

However, I just noticed the updateAll method is currently marked //TODO for the pro driver. 
Could I used the code from the open driver to drive a pro ?

**Comment by wiedi** [comment]
Yes, I've also fixed that with 14f33da4dc5580ad8bf5f9caca8997190324871a.
