### ISSUE TITLE
easing not working in animations

### ISSUE THREAD

**Issue by seriousManual** [wiedi/node-dmx#67]
Hello,
easing is not working in animations because the options field is ignored when setting up the animation.

**Comment by Fensterbank** [comment]
@seriousManual Nice catch, thanks!

We are getting the option and setting a default value for it
https://github.com/wiedi/node-dmx/blob/5b28517c718fb2d28f1495d55be61bcbee08705f/anim.js#L14

but finally a hard coded string `linear` is used.
https://github.com/wiedi/node-dmx/blob/5b28517c718fb2d28f1495d55be61bcbee08705f/anim.js#L52

Quite easy to fix. First come first serve.

**Comment by seriousManual** [comment]
I took the liberty and created a PR :)
